modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="hezbin"
version="1.0.0"
displayName="hezbin"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="edouardsharma, MCreator"

[[dependencies.hezbin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



